# Generated by Django 3.2.8 on 2021-10-16 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radio2playlist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='start_time',
            field=models.DateTimeField(db_index=True),
        ),
    ]
