# Generated by Django 3.2.8 on 2021-10-17 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('radio2playlist', '0002_alter_playlist_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='station',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='radio2playlist.station'),
        ),
    ]
