# Generated by Django 3.2.8 on 2021-10-17 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('radio2playlist', '0003_show_station'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='artist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='tracks', to='radio2playlist.artist'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='show',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='playlists', to='radio2playlist.show'),
        ),
        migrations.AlterField(
            model_name='playlistitem',
            name='playlist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='songs', to='radio2playlist.playlist'),
        ),
        migrations.AlterField(
            model_name='show',
            name='station',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='shows', to='radio2playlist.station'),
        ),
    ]
